# List of required/used R packages

library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(plotly)
library(shiny)
library(shinydashboard)
library(shinyalert)
library(shinythemes)
library(shinyWidgets)
library(leaflet)
library(DT)
library(jsonlite)
library(htmltools)
